version: "3.8"
services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    volumes:
      - /tmp/postgres_data_users/:/var/lib/postgresql/data
      - ${PWD}/db/:/tmp/
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
    networks:
      - deno-demo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - deno-demo
  app:
    build: 
      context: .
    restart: always
    networks:
      - deno-demo
    environment:
      DATABASE_URL: postgresql://demo:demo@postgres:5432/demo

networks:
  deno-demo:
    driver: bridge