# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  DATABASE_URL: postgres://whatdo:youmean@localhost/potato


jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: whatdo
          POSTGRES_DB: potato
          POSTGRES_PASSWORD: youmean

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          deno cache src/main.ts
          deno test --allow-env=DATABASE_URL --allow-net=loremricksum.com,localhost
  package:
    needs: test 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build
        run: docker build -t ghcr.io/modulus/deno-postgres-demo:latest -f Dockerfile.node .
      - name: Docker push
        run: docker push ghcr.io/modulus/deno-postgres-demo:latest
