name: Tags

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"
  pull_request:
    tags: 
      - "[0-9].[0-9].[0-9]"
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: whatdo
          POSTGRES_DB: potato
          POSTGRES_PASSWORD: youmean

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          deno cache src/main.ts
          deno test --allow-env=DATABASE_URL --allow-net=loremricksum.com,localhost
  package:
    needs: test 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}               
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build
        run: docker build -t ghcr.io/modulus/deno-postgres-demo:${{ steps.vars.outputs.tag }} -f Dockerfile .
      - name: Docker push
        run: docker push ghcr.io/modulus/deno-postgres-demo:${{ steps.vars.outputs.tag }}

